package fi.paso.pagevox.ui.theme

import androidx.compose.ui.graphics.Color

// Complete Material 3 baseline color roles. These are the static fallback used
// on devices that don't support dynamic color (Material You, Android 11 and
// below). Every role the M3 spec defines is provided so components render with
// the correct tonal relationships instead of relying on library defaults.

// --- Light scheme ---
val md_light_primary = Color(0xFF6750A4)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFEADDFF)
val md_light_onPrimaryContainer = Color(0xFF21005D)
val md_light_secondary = Color(0xFF625B71)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFE8DEF8)
val md_light_onSecondaryContainer = Color(0xFF1D192B)
val md_light_tertiary = Color(0xFF7D5260)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFFFD8E4)
val md_light_onTertiaryContainer = Color(0xFF31111D)
val md_light_error = Color(0xFFB3261E)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFF9DEDC)
val md_light_onErrorContainer = Color(0xFF410E0B)
val md_light_background = Color(0xFFFEF7FF)
val md_light_onBackground = Color(0xFF1D1B20)
val md_light_surface = Color(0xFFFEF7FF)
val md_light_onSurface = Color(0xFF1D1B20)
val md_light_surfaceVariant = Color(0xFFE7E0EC)
val md_light_onSurfaceVariant = Color(0xFF49454F)
val md_light_outline = Color(0xFF79747E)
val md_light_outlineVariant = Color(0xFFCAC4D0)
val md_light_scrim = Color(0xFF000000)
val md_light_inverseSurface = Color(0xFF322F35)
val md_light_inverseOnSurface = Color(0xFFF5EFF7)
val md_light_inversePrimary = Color(0xFFD0BCFF)
val md_light_surfaceDim = Color(0xFFDED8E1)
val md_light_surfaceBright = Color(0xFFFEF7FF)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow = Color(0xFFF7F2FA)
val md_light_surfaceContainer = Color(0xFFF3EDF7)
val md_light_surfaceContainerHigh = Color(0xFFECE6F0)
val md_light_surfaceContainerHighest = Color(0xFFE6E0E9)

// --- Dark scheme ---
val md_dark_primary = Color(0xFFD0BCFF)
val md_dark_onPrimary = Color(0xFF381E72)
val md_dark_primaryContainer = Color(0xFF4F378B)
val md_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_dark_secondary = Color(0xFFCCC2DC)
val md_dark_onSecondary = Color(0xFF332D41)
val md_dark_secondaryContainer = Color(0xFF4A4458)
val md_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_dark_tertiary = Color(0xFFEFB8C8)
val md_dark_onTertiary = Color(0xFF492532)
val md_dark_tertiaryContainer = Color(0xFF633B48)
val md_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val md_dark_error = Color(0xFFF2B8B5)
val md_dark_onError = Color(0xFF601410)
val md_dark_errorContainer = Color(0xFF8C1D18)
val md_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_dark_background = Color(0xFF141218)
val md_dark_onBackground = Color(0xFFE6E0E9)
val md_dark_surface = Color(0xFF141218)
val md_dark_onSurface = Color(0xFFE6E0E9)
val md_dark_surfaceVariant = Color(0xFF49454F)
val md_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_dark_outline = Color(0xFF938F99)
val md_dark_outlineVariant = Color(0xFF49454F)
val md_dark_scrim = Color(0xFF000000)
val md_dark_inverseSurface = Color(0xFFE6E0E9)
val md_dark_inverseOnSurface = Color(0xFF322F35)
val md_dark_inversePrimary = Color(0xFF6750A4)
val md_dark_surfaceDim = Color(0xFF141218)
val md_dark_surfaceBright = Color(0xFF3B383E)
val md_dark_surfaceContainerLowest = Color(0xFF0F0D13)
val md_dark_surfaceContainerLow = Color(0xFF1D1B20)
val md_dark_surfaceContainer = Color(0xFF211F26)
val md_dark_surfaceContainerHigh = Color(0xFF2B2930)
val md_dark_surfaceContainerHighest = Color(0xFF36343B)
