plugins {
    // Applies the Android Application plugin, which is required for building an Android app.
    // Kotlin support is provided built-in by AGP 9+, so no separate kotlin-android plugin.
    alias(libs.plugins.android.application)

    // Applies the Kotlin Compose plugin, which is necessary for using Jetpack Compose.
    alias(libs.plugins.kotlin.compose)
}

android {
    // Sets the namespace for the application, used for R class generation.
    namespace = "fi.paso.pagevox"
    // Sets the Android SDK version to compile against.
    compileSdk = 36

    defaultConfig {
        // A unique identifier for the application in the Google Play Store.
        applicationId = "fi.paso.pagevox"
        // The minimum Android API level required to run the app.
        minSdk = 26
        // The target Android API level for the app.
        targetSdk = 36
        // An internal version number for the app.
        versionCode = 6
        // A user-facing version number for the app.
        versionName = "1.5"

        // The fully qualified class name of the test instrumentation runner.
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            // Enables the use of vector drawables on older Android versions.
            useSupportLibrary = true
        }
    }

    buildTypes {
        // Configuration for the 'release' build type.
        release {
            // Disables code shrinking and obfuscation for the release build.
            isMinifyEnabled = false
            // Specifies the ProGuard configuration files to use.
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        // Sets the Java language version for the source code.
        sourceCompatibility = JavaVersion.VERSION_1_8
        // Sets the Java language version for the generated bytecode.
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    buildFeatures {
        // Enables Jetpack Compose for the project.
        compose = true
    }
    // Kotlin's jvmTarget defaults to compileOptions.targetCompatibility (1.8), and
    // the Compose compiler is configured by the kotlin-compose plugin, so neither
    // a kotlinOptions nor a composeOptions block is needed.
    packaging {
        resources {
            // Excludes specific files from the final APK to avoid conflicts.
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    androidResources {
        ignoreAssetsPattern =
            "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~:!desktop.ini"
    }

    // Ensure desktop.ini is ignored by AAPT
}

dependencies {
    // media3 for media playback
    implementation("androidx.media3:media3-exoplayer:1.4.0")
    implementation("androidx.media3:media3-session:1.4.0")
    implementation("androidx.media3:media3-ui:1.4.0")

    // Core Kotlin extensions
    implementation(libs.androidx.core.ktx)
    // Lifecycle runtime for observing component lifecycles
    implementation(libs.androidx.lifecycle.runtime.ktx)
    // Activity Compose for integrating Compose with Activities
    implementation(libs.androidx.activity.compose)
    // Compose Bill of Materials (BOM) to manage Compose dependency versions
    implementation(platform(libs.androidx.compose.bom))
    // Core Compose UI library
    implementation(libs.androidx.compose.ui)
    // Compose UI graphics library
    implementation(libs.androidx.compose.ui.graphics)
    // Compose UI tooling for previews
    implementation(libs.androidx.compose.ui.tooling.preview)
    // Material Design 3 components for Compose
    implementation(libs.androidx.compose.material3)
    // Extended Material icons for Compose (version managed by the Compose BOM)
    implementation("androidx.compose.material:material-icons-extended")
    // DataStore for storing key-value pairs
    implementation("androidx.datastore:datastore-preferences:1.1.1")
    // Jsoup for parsing HTML
    implementation("org.jsoup:jsoup:1.18.1")
    // WebKit compat for native WebView dark rendering (algorithmic darkening)
    implementation("androidx.webkit:webkit:1.16.0")
    // ViewModel integration for Compose
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.3")
    // Lifecycle runtime integration for Compose
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.3")

    // Dependencies for unit tests
    testImplementation(libs.junit)

    // Dependencies for Android instrumentation tests
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)

    // Dependencies for debug builds
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}

// Task to aggressively delete desktop.ini files before build starts
tasks.register("deleteDesktopIni") {
    doFirst {
        println("Scanning for and deleting desktop.ini files...")
        val files = fileTree(layout.projectDirectory.dir("..")) {
            include("**/desktop.ini")
            exclude("**/build/**", "**/.git/**", "**/.gradle/**")
        }
        files.forEach { file ->
            try {
                if (file.exists() && file.delete()) {
                    println("Deleted: ${file.absolutePath}")
                }
            } catch (e: Exception) {
                println("Failed to delete ${file.absolutePath}: $e")
            }
        }
    }
}

// Ensure this task runs before any build tasks
tasks.named("preBuild") {
    dependsOn("deleteDesktopIni")
}